# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 12:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TODO', '0002_auto_20160601_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='description',
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='duedate',
            field=models.DateField(default=datetime.datetime(2016, 6, 1, 12, 45, 35, 478000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateField(default=datetime.datetime(2016, 6, 1, 12, 45, 35, 479000, tzinfo=utc)),
        ),
    ]
