# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-07 04:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TODO', '0004_auto_20160601_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='item',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='li',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TODO.TodoList'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='duedate',
            field=models.DateField(default=datetime.datetime(2016, 6, 7, 4, 2, 17, 684000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateField(default=datetime.datetime(2016, 6, 7, 4, 2, 17, 683000, tzinfo=utc)),
        ),
    ]
