# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-07 04:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TODO', '0005_auto_20160607_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='created',
            field=models.DateField(default=datetime.datetime(2016, 6, 7, 4, 11, 33, 339000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='duedate',
            field=models.DateField(default=datetime.datetime(2016, 6, 7, 4, 11, 33, 339000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateField(default=datetime.datetime(2016, 6, 7, 4, 11, 33, 338000, tzinfo=utc)),
        ),
    ]
